## Pirus Encoding Script

library(readxl)
library(tidyverse)

pirus <- read_excel("PIRUS V5.xlsx")

pirus_encoded <- pirus %>% 
  mutate(Plot_Target1 = case_when(
    Plot_Target1 == 1 ~ "Businesses",
    Plot_Target1 == 2 ~ "Government (General)",
    Plot_Target1 == 3 ~ "Police",
    Plot_Target1 == 4 ~ "Military",
    Plot_Target1 == 5 ~ "Abortion", # Abortion-related targets
    Plot_Target1 == 6 ~ "Airports/Aircraft",
    Plot_Target1 == 7 ~ "Government (Diplomatic)",
    Plot_Target1 == 8 ~ "Education", # Educational institutions
    Plot_Target1 == 9 ~ "Food/Water", # Food and water supply target
    Plot_Target1 == 10 ~ "Media", # Journalists and Media
    Plot_Target1 == 11 ~ "Maritime", # Ports and maritime facilities
    Plot_Target1 == 12 ~ "NGO",
    Plot_Target1 == 13 ~ "Public Services", # Ambulances, firefighters, etc.
    Plot_Target1 == 14 ~ "Private", # Private citizens or property
    Plot_Target1 == 15 ~ "Religion", # Religious figures and institutions
    Plot_Target1 == 16 ~ "Telecommunication",
    Plot_Target1 == 17 ~ "Terrorists",
    Plot_Target1 == 18 ~ "Tourists",
    Plot_Target1 == 19 ~ "Transportation",
    Plot_Target1 == 20 ~ "Utilities",
    Plot_Target1 == -88 ~ "No Plot",
    Plot_Target1 == -99 ~ "Unknown",
    Plot_Target1 == NA ~ NA
  ),
  Plot_Target1 = as.factor(Plot_Target1),
  Plot_Target1 = fct_relevel(Plot_Target1, "Businesses"),
  Plot_Target2 = case_when(
    Plot_Target2 == 1 ~ "Businesses",
    Plot_Target2 == 2 ~ "Government (General)",
    Plot_Target2 == 3 ~ "Police",
    Plot_Target2 == 4 ~ "Military",
    Plot_Target2 == 5 ~ "Abortion", # Abortion-related targets
    Plot_Target2 == 6 ~ "Airports/Aircraft",
    Plot_Target2 == 7 ~ "Government (Diplomatic)",
    Plot_Target2 == 8 ~ "Education", # Educational institutions
    Plot_Target2 == 9 ~ "Food/Water", # Food and water supply target
    Plot_Target2 == 10 ~ "Media", # Journalists and Media
    Plot_Target2 == 11 ~ "Maritime", # Ports and maritime facilities
    Plot_Target2 == 12 ~ "NGO",
    Plot_Target2 == 13 ~ "Public Services", # Ambulances, firefighters, etc.
    Plot_Target2 == 14 ~ "Private", # Private citizens or property
    Plot_Target2 == 15 ~ "Religion", # Religious figures and institutions
    Plot_Target2 == 16 ~ "Telecommunication",
    Plot_Target2 == 17 ~ "Terrorists",
    Plot_Target2 == 18 ~ "Tourists",
    Plot_Target2 == 19 ~ "Transportation",
    Plot_Target2 == 20 ~ "Utilities",
    Plot_Target2 == -88 ~ "No Plot",
    Plot_Target2 == -99 ~ "Unknown",
    Plot_Target2 == NA ~ NA
  ),
  Plot_Target2 = as.factor(Plot_Target2),
  Plot_Target3 = case_when(
    Plot_Target3 == 1 ~ "Businesses",
    Plot_Target3 == 2 ~ "Government (General)",
    Plot_Target3 == 3 ~ "Police",
    Plot_Target3 == 4 ~ "Military",
    Plot_Target3 == 5 ~ "Abortion", # Abortion-related targets
    Plot_Target3 == 6 ~ "Airports/Aircraft",
    Plot_Target3 == 7 ~ "Government (Diplomatic)",
    Plot_Target3 == 8 ~ "Education", # Educational institutions
    Plot_Target3 == 9 ~ "Food/Water", # Food and water supply target
    Plot_Target3 == 10 ~ "Media", # Journalists and Media
    Plot_Target3 == 11 ~ "Maritime", # Ports and maritime facilities
    Plot_Target3 == 12 ~ "NGO",
    Plot_Target3 == 13 ~ "Public Services", # Ambulances, firefighters, etc.
    Plot_Target3 == 14 ~ "Private", # Private citizens or property
    Plot_Target3 == 15 ~ "Religion", # Religious figures and institutions
    Plot_Target3 == 16 ~ "Telecommunication",
    Plot_Target3 == 17 ~ "Terrorists",
    Plot_Target3 == 18 ~ "Tourists",
    Plot_Target3 == 19 ~ "Transportation",
    Plot_Target3 == 20 ~ "Utilities",
    Plot_Target3 == -88 ~ "No Plot",
    Plot_Target3 == -99 ~ "Unknown",
    Plot_Target3 == NA ~ NA
  ),
  Plot_Target3 = as.factor(Plot_Target3),
  Attack_Preparation = case_when(
    Attack_Preparation == 0 ~ "None",
    Attack_Preparation == 1 ~ "Moderate",
    Attack_Preparation == 2 ~ "Extensive",
    Attack_Preparation == -99 ~ "Unknown",
    Attack_Preparation == -88 ~ "No Plot",
    Attack_Preparation == NA ~ NA
  ),
  Attack_Preparation = as.factor(Attack_Preparation),
  Attack_Preparation = fct_relevel(Attack_Preparation, "None"),
  Changing_Target = case_when(
    Changing_Target == 0 ~ "No",
    Changing_Target == 1 ~ "Yes",
    Changing_Target == -99 ~ "Unknown",
    Changing_Target == -88 ~ "No Plot"
  ),
  Changing_Target = as.factor(Changing_Target),
  Changing_Target = fct_relevel(Changing_Target, "No"),
  Anticp_Fatals_Targ = case_when(
    Anticp_Fatals_Targ == 0 ~ "None",
    Anticp_Fatals_Targ == 1 ~ "1 to 20",
    Anticp_Fatals_Targ == 2 ~ "> 20",
    Anticp_Fatals_Targ == 3 ~ "> 100",
    Anticp_Fatals_Targ == -99 ~ "Unknown",
    Anticp_Fatals_Targ == -88 ~ "No Plot"
  ),
  Anticp_Fatals_Targ = as.factor(Anticp_Fatals_Targ),
  Anticp_Fatals_Targ = fct_relevel(Anticp_Fatals_Targ, "None"),
  Internet_Use_Plot = case_when(
    Internet_Use_Plot == 0 ~ "No",
    Internet_Use_Plot == 1 ~ "Yes",
    Internet_Use_Plot == -99 ~ "Unknown",
    Internet_Use_Plot == -88 ~ "Not Applicable"
  ),
  Internet_Use_Plot = as.factor(Internet_Use_Plot),
  Internet_Use_Plot = fct_relevel(Internet_Use_Plot, "No"),
  Extent_Plot = case_when(
    Extent_Plot == 0 ~ "No plot",
    Extent_Plot == 1 ~ "Nebulous plot",
    Extent_Plot == 2 ~ "Attempted Acquisition",
    Extent_Plot == 3 ~ "Acquisition",
    Extent_Plot == 4 ~ "Failed",
    Extent_Plot == 5 ~ "Successful",
    Extent_Plot == -99 ~ "Unknown"
  ),
  Extent_Plot = as.factor(Extent_Plot),
  Extent_Plot = fct_relevel(Extent_Plot, "No plot"),
  Violent = case_when(
    Violent == 0 ~ "No",
    Violent == 1 ~ "Yes"
  ),
  Violent = as.factor(Violent),
  Violent = fct_relevel(Violent, "No"),
  Primary_Event_Mass_Casualty_Incident = case_when(
    Primary_Event_Mass_Casualty_Incident == 0 ~ "No",
    Primary_Event_Mass_Casualty_Incident == 1 ~ "Yes",
    Primary_Event_Mass_Casualty_Incident == -88 ~ "Not Applicable"
  ),
  Primary_Event_Mass_Casualty_Incident = as.factor(Primary_Event_Mass_Casualty_Incident),
  Primary_Event_Mass_Casualty_Incident = fct_relevel(Primary_Event_Mass_Casualty_Incident, "No"),
  Primary_Event_Mass_Casualty_Incident_Type = case_when(
    Primary_Event_Mass_Casualty_Incident_Type == 0 ~ "Failed",
    Primary_Event_Mass_Casualty_Incident_Type == 1 ~ "Successful",
    Primary_Event_Mass_Casualty_Incident_Type == -88 ~ "Not Applicable"
  ),
  Primary_Event_Mass_Casualty_Incident_Type = as.factor(Primary_Event_Mass_Casualty_Incident_Type),
  Primary_Event_Mass_Casualty_Incident_Type = fct_relevel(Primary_Event_Mass_Casualty_Incident_Type, "Failed"),
  Primary_Event_Mass_Casualty_Incident_Killed = case_when(
    Primary_Event_Mass_Casualty_Incident_Killed == 0 ~ "No",
    Primary_Event_Mass_Casualty_Incident_Killed == 1 ~ "Yes",
    Primary_Event_Mass_Casualty_Incident_Killed == -88 ~ "Not Applicable"
  ),
  Primary_Event_Mass_Casualty_Incident_Killed = as.factor(Primary_Event_Mass_Casualty_Incident_Killed),
  Primary_Event_Mass_Casualty_Incident_Killed = fct_relevel(Primary_Event_Mass_Casualty_Incident_Killed, "No"),
  Foreign_Fighter = case_when(
    Foreign_Fighter == 0 ~ "No",
    Foreign_Fighter == 1 ~ "Yes"
  ),
  Foreign_Fighter = as.factor(Foreign_Fighter),
  Criminal_Severity = case_when(
    Criminal_Severity == 0 ~ "Non-criminal",
    Criminal_Severity == 1 ~ "Conspiracy ex-post", # Making false statements, etc
    Criminal_Severity == 2 ~ "Illegal Protest", # Or criminal trespassing
    Criminal_Severity == 3 ~ "White-collar",
    Criminal_Severity == 4 ~ "Recruiting",
    Criminal_Severity == 5 ~ "Training",
    Criminal_Severity == 6 ~ "Threatening (Mis.)",
    Criminal_Severity == 7 ~ "Conspiracy (Violent)",
    Criminal_Severity == 8 ~ "Threatening (Fel.)",
    Criminal_Severity == 9 ~ "Property Violence",
    Criminal_Severity == 10 ~ "Personal Violence",
    Criminal_Severity == -99 ~ "Unknown"
  ),
  Criminal_Severity = as.factor(Criminal_Severity),
  Criminal_Severity = fct_relevel(Criminal_Severity, "Non-criminal"),
  Criminal_Charges = case_when(
    Criminal_Charges == 1 ~ "Misdemeanor",
    Criminal_Charges == 2 ~ "Felony",
    Criminal_Charges == 3 ~ "Unknown",
    Criminal_Charges == 4 ~ "No charges",
    Criminal_Charges == -99 ~ "Unknown"
  ),
  Criminal_Charges = as.factor(Criminal_Charges),
  Criminal_Charges = fct_relevel(Criminal_Charges, "No charges"),
  Indict_Arrest = case_when(
    Indict_Arrest == 1 ~ "Arrested only",
    Indict_Arrest == 2 ~ "Arrested, indict NA",
    Indict_Arrest == 3 ~ "Indicted only",
    Indict_Arrest == 4 ~ "Indicted and arrested",
    Indict_Arrest == -99 ~ "Unknown",
    Indict_Arrest == -88 ~ "No"
  ),
  Indict_Arrest = as.factor(Indict_Arrest),
  Indict_Arrest = fct_relevel(Indict_Arrest, "Arrested only"),
  Current_Status = case_when(
    Current_Status == 1 ~ "Unpursued",
    Current_Status == 2 ~ "Pursued",
    Current_Status == 3 ~ "Arrested",
    Current_Status == 4 ~ "Convicted",
    Current_Status == 5 ~ "Acquitted",
    Current_Status == 6 ~ "Dead (nat. causes)",
    Current_Status == 7 ~ "Dead (suicide)",
    Current_Status == 8 ~ "Killed (LawEnf/Mil)",
    Current_Status == 9 ~ "Killed (Adversary)",
    Current_Status == -99 ~ "Unknown"
  ),
  Current_Status = as.factor(Current_Status),
  Current_Status = fct_relevel(Current_Status, "Unpursued"),
  Group_Membership = case_when(
    Group_Membership == 0 ~ "No",
    Group_Membership == 1 ~ "Above-Ground",
    Group_Membership == 2 ~ "Informal Group",
    Group_Membership == 3 ~ "Extremist Group",
    Group_Membership == -99 ~ "Unknown"
  ),
  Group_Membership = as.factor(Group_Membership),
  Group_Membership = fct_relevel(Group_Membership, "No"),
  Actively_Recruited = case_when(
    Actively_Recruited == 0 ~ "No",
    Actively_Recruited == 1 ~ "Yes",
    Actively_Recruited == -99 ~ "Unknown"
  ),
  Actively_Recruited = as.factor(Actively_Recruited),
  Actively_Recruited = fct_relevel(Actively_Recruited, "No"),
  Recruiter1 = case_when(
    Recruiter1 == 1 ~ "Group Member",
    Recruiter1 == 2 ~ "Family Member",
    Recruiter1 == 3 ~ "Friend",
    Recruiter1 == 4 ~ "Other",
    Recruiter1 == -99 ~ "Unknown",
    Recruiter1 == -88 ~ "Not recruited"
  ),
  Recruiter1 = as.factor(Recruiter1),
  Recruiter1 = fct_relevel(Recruiter1, "Group Member"),
  Recruiter2 = case_when(
    Recruiter2 == 1 ~ "Group Member",
    Recruiter2 == 2 ~ "Family Member",
    Recruiter2 == 3 ~ "Friend",
    Recruiter2 == 4 ~ "Other",
    Recruiter2 == -99 ~ "Unknown",
    Recruiter2 == NA ~ NA
  ),
  Recruiter2 = as.factor(Recruiter2),
  Recruiter2 = fct_relevel(Recruiter2, "Group Member"),
  Recruiter3 = case_when(
    Recruiter3 == 1 ~ "Group Member",
    Recruiter3 == 2 ~ "Family Member",
    Recruiter3 == 3 ~ "Friend",
    Recruiter3 == 4 ~ "Other",
    Recruiter3 == -99 ~ "Unknown",
    Recruiter3 == -88 ~ "Not recruited",
    Recruiter3 == NA ~ NA
  ),
  Recruiter3 = as.factor(Recruiter3),
  Recruiter3 = fct_relevel(Recruiter3, "Group Member"),
  Actively_Connect = case_when(
    Actively_Connect == 0 ~ "No",
    Actively_Connect == 1 ~ "Yes (prior)",
    Actively_Connect == 2 ~ "Yes (post)",
    Actively_Connect == -99 ~ "Unknown"
  ),
  Actively_Connect = as.factor(Actively_Connect),
  Actively_Connect = fct_relevel(Actively_Connect, "No"),
  Group_Competition = case_when(
    Group_Competition == 0 ~ "No",
    Group_Competition == 1 ~ "Yes",
    Group_Competition == -99 ~ "Unknown",
    Group_Competition == -88 ~ "No group"
  ),
  Group_Competition = as.factor(Group_Competition),
  Group_Competition = fct_relevel(Group_Competition, "No"),
  Role_Group = case_when(
    Role_Group == 1 ~ "Loose Associate",
    Role_Group == 2 ~ "Follower",
    Role_Group == 3 ~ "Leader",
    Role_Group == -99 ~ "Unknown",
    Role_Group == -88 ~ "No group"
  ),
  Role_Group = as.factor(Role_Group),
  Role_Group = fct_relevel(Role_Group, "Loose Associate"),
  Clique = case_when(
    Clique == 0 ~ "No",
    Clique == 1 ~ "Yes"
  ),
  Clique = as.factor(Clique),
  Internet_Radicalization = case_when(
    Internet_Radicalization == 0 ~ "No role",
    Internet_Radicalization == 1 ~ "Some role",
    Internet_Radicalization == 2 ~ "Primary means",
    Internet_Radicalization == -99 ~ "Unknown",
    Internet_Radicalization == -88 ~ "Not applicable"
  ),
  Internet_Radicalization = as.factor(Internet_Radicalization),
  Internet_Radicalization = fct_relevel(Internet_Radicalization, "No role"),
  Media_Radicalization = case_when(
    Media_Radicalization == 0 ~ "No role",
    Media_Radicalization == 1 ~ "Some role",
    Media_Radicalization == 2 ~ "Primary means",
    Media_Radicalization == -99 ~ "Unknown"
  ),
  Media_Radicalization = as.factor(Media_Radicalization),
  Media_Radicalization = fct_relevel(Media_Radicalization, "No role"),
  Social_Media = case_when(
    Social_Media == 0 ~ "No",
    Social_Media == 1 ~ "Some role",
    Social_Media == 2 ~ "Primary means",
    Social_Media == -99 ~ "Unknown",
    Social_Media == -88 ~ "Not applicable"
  ),
  Social_Media = as.factor(Social_Media),
  Social_Media = fct_relevel(Social_Media, "No"),
  Social_Media_Frequency = case_when(
    Social_Media_Frequency == 1 ~ "Rarely",
    Social_Media_Frequency == 2 ~ "Sporadically",
    Social_Media_Frequency == 3 ~ "Occasionally",
    Social_Media_Frequency == 4 ~ "Frequently",
    Social_Media_Frequency == 5 ~ "Continually",
    Social_Media_Frequency == -99 ~ "Unknown",
    Social_Media_Frequency == -88 ~ "Not applicable"
  ),
  Social_Media_Frequency = as.factor(Social_Media_Frequency),
  Social_Media_Frequency = fct_relevel(Social_Media_Frequency, "Rarely"),
  Social_Media_Platform1 = case_when(
    Social_Media_Platform1 == 1 ~ "Facebook",
    Social_Media_Platform1 == 2 ~ "Twitter",
    Social_Media_Platform1 == 3 ~ "YouTube",
    Social_Media_Platform1 == 4 ~ "Vimeo",
    Social_Media_Platform1 == 5 ~ "Instagram",
    Social_Media_Platform1 == 6 ~ "Flickr",
    Social_Media_Platform1 == 7 ~ "Tumblr",
    Social_Media_Platform1 == 8 ~ "Imgur",
    Social_Media_Platform1 == 9 ~ "Snapchat",
    Social_Media_Platform1 == 10 ~ "Google Plus",
    Social_Media_Platform1 == 11 ~ "Skype",
    Social_Media_Platform1 == 12 ~ "LinkedIn",
    Social_Media_Platform1 == 13 ~ "MySpace",
    Social_Media_Platform1 == 14 ~ "4chan",
    Social_Media_Platform1 == 15 ~ "Reddit",
    Social_Media_Platform1 == 16 ~ "Ask.fm",
    Social_Media_Platform1 == 17 ~ "WhatsApp",
    Social_Media_Platform1 == 18 ~ "Surespot",
    Social_Media_Platform1 == 19 ~ "Telegram",
    Social_Media_Platform1 == 20 ~ "Kik",
    Social_Media_Platform1 == 21 ~ "Paltalk",
    Social_Media_Platform1 == 22 ~ "VK",
    Social_Media_Platform1 == 23 ~ "Diaspora",
    Social_Media_Platform1 == 24 ~ "JustPaste.it",
    Social_Media_Platform1 == 25 ~ "SoundCloud",
    Social_Media_Platform1 == 26 ~ "Blogging Sites",
    Social_Media_Platform1 == 27 ~ "Other",
    Social_Media_Platform1 == 28 ~ "Dark web",
    Social_Media_Platform1 == 29 ~ "Discord",
    Social_Media_Platform1 == 30 ~ "Gab",
    Social_Media_Platform1 == 31 ~ "Iron March",
    Social_Media_Platform1 == 32 ~ "Parler",
    Social_Media_Platform1 == 33 ~ "Wire",
    Social_Media_Platform1 == -99 ~ "Unknown",
    Social_Media_Platform1 == -88 ~ "None"
  ),
  Social_Media_Platform1 = as.factor(Social_Media_Platform1),
  Social_Media_Platform1 = fct_relevel(Social_Media_Platform1, "Facebook"),
  Social_Media_Platform2 = case_when(
    Social_Media_Platform2 == 1 ~ "Facebook",
    Social_Media_Platform2 == 2 ~ "Twitter",
    Social_Media_Platform2 == 3 ~ "YouTube",
    Social_Media_Platform2 == 4 ~ "Vimeo",
    Social_Media_Platform2 == 5 ~ "Instagram",
    Social_Media_Platform2 == 6 ~ "Flickr",
    Social_Media_Platform2 == 7 ~ "Tumblr",
    Social_Media_Platform2 == 8 ~ "Imgur",
    Social_Media_Platform2 == 9 ~ "Snapchat",
    Social_Media_Platform2 == 10 ~ "Google Plus",
    Social_Media_Platform2 == 11 ~ "Skype",
    Social_Media_Platform2 == 12 ~ "LinkedIn",
    Social_Media_Platform2 == 13 ~ "MySpace",
    Social_Media_Platform2 == 14 ~ "4chan",
    Social_Media_Platform2 == 15 ~ "Reddit",
    Social_Media_Platform2 == 16 ~ "Ask.fm",
    Social_Media_Platform2 == 17 ~ "WhatsApp",
    Social_Media_Platform2 == 18 ~ "Surespot",
    Social_Media_Platform2 == 19 ~ "Telegram",
    Social_Media_Platform2 == 20 ~ "Kik",
    Social_Media_Platform2 == 21 ~ "Paltalk",
    Social_Media_Platform2 == 22 ~ "VK",
    Social_Media_Platform2 == 23 ~ "Diaspora",
    Social_Media_Platform2 == 24 ~ "JustPaste.it",
    Social_Media_Platform2 == 25 ~ "SoundCloud",
    Social_Media_Platform2 == 26 ~ "Blogging Sites",
    Social_Media_Platform2 == 27 ~ "Other",
    Social_Media_Platform2 == 28 ~ "Dark web",
    Social_Media_Platform2 == 29 ~ "Discord",
    Social_Media_Platform2 == 30 ~ "Gab",
    Social_Media_Platform2 == 31 ~ "Iron March",
    Social_Media_Platform2 == 32 ~ "Parler",
    Social_Media_Platform2 == 33 ~ "Wire",
    Social_Media_Platform2 == -99 ~ "Unknown",
    Social_Media_Platform2 == NA ~ NA
  ),
  Social_Media_Platform2 = as.factor(Social_Media_Platform2),
  Social_Media_Platform2 = fct_relevel(Social_Media_Platform2, "Facebook"),
  Social_Media_Platform3 = case_when(
    Social_Media_Platform3 == 1 ~ "Facebook",
    Social_Media_Platform3 == 2 ~ "Twitter",
    Social_Media_Platform3 == 3 ~ "YouTube",
    Social_Media_Platform3 == 4 ~ "Vimeo",
    Social_Media_Platform3 == 5 ~ "Instagram",
    Social_Media_Platform3 == 6 ~ "Flickr",
    Social_Media_Platform3 == 7 ~ "Tumblr",
    Social_Media_Platform3 == 8 ~ "Imgur",
    Social_Media_Platform3 == 9 ~ "Snapchat",
    Social_Media_Platform3 == 10 ~ "Google Plus",
    Social_Media_Platform3 == 11 ~ "Skype",
    Social_Media_Platform3 == 12 ~ "LinkedIn",
    Social_Media_Platform3 == 13 ~ "MySpace",
    Social_Media_Platform3 == 14 ~ "4chan",
    Social_Media_Platform3 == 15 ~ "Reddit",
    Social_Media_Platform3 == 16 ~ "Ask.fm",
    Social_Media_Platform3 == 17 ~ "WhatsApp",
    Social_Media_Platform3 == 18 ~ "Surespot",
    Social_Media_Platform3 == 19 ~ "Telegram",
    Social_Media_Platform3 == 20 ~ "Kik",
    Social_Media_Platform3 == 21 ~ "Paltalk",
    Social_Media_Platform3 == 22 ~ "VK",
    Social_Media_Platform3 == 23 ~ "Diaspora",
    Social_Media_Platform3 == 24 ~ "JustPaste.it",
    Social_Media_Platform3 == 25 ~ "SoundCloud",
    Social_Media_Platform3 == 26 ~ "Blogging Sites",
    Social_Media_Platform3 == 27 ~ "Other",
    Social_Media_Platform3 == 28 ~ "Dark web",
    Social_Media_Platform3 == 29 ~ "Discord",
    Social_Media_Platform3 == 30 ~ "Gab",
    Social_Media_Platform3 == 31 ~ "Iron March",
    Social_Media_Platform3 == 32 ~ "Parler",
    Social_Media_Platform3 == 33 ~ "Wire",
    Social_Media_Platform3 == -99 ~ "Unknown",
    Social_Media_Platform3 == NA ~ NA
  ),
  Social_Media_Platform3 = as.factor(Social_Media_Platform3),
  Social_Media_Platform3 = fct_relevel(Social_Media_Platform3, "Facebook"),
  Social_Media_Platform4 = case_when(
    Social_Media_Platform4 == 1 ~ "Facebook",
    Social_Media_Platform4 == 2 ~ "Twitter",
    Social_Media_Platform4 == 3 ~ "YouTube",
    Social_Media_Platform4 == 4 ~ "Vimeo",
    Social_Media_Platform4 == 5 ~ "Instagram",
    Social_Media_Platform4 == 6 ~ "Flickr",
    Social_Media_Platform4 == 7 ~ "Tumblr",
    Social_Media_Platform4 == 8 ~ "Imgur",
    Social_Media_Platform4 == 9 ~ "Snapchat",
    Social_Media_Platform4 == 10 ~ "Google Plus",
    Social_Media_Platform4 == 11 ~ "Skype",
    Social_Media_Platform4 == 12 ~ "LinkedIn",
    Social_Media_Platform4 == 13 ~ "MySpace",
    Social_Media_Platform4 == 14 ~ "4chan",
    Social_Media_Platform4 == 15 ~ "Reddit",
    Social_Media_Platform4 == 16 ~ "Ask.fm",
    Social_Media_Platform4 == 17 ~ "WhatsApp",
    Social_Media_Platform4 == 18 ~ "Surespot",
    Social_Media_Platform4 == 19 ~ "Telegram",
    Social_Media_Platform4 == 20 ~ "Kik",
    Social_Media_Platform4 == 21 ~ "Paltalk",
    Social_Media_Platform4 == 22 ~ "VK",
    Social_Media_Platform4 == 23 ~ "Diaspora",
    Social_Media_Platform4 == 24 ~ "JustPaste.it",
    Social_Media_Platform4 == 25 ~ "SoundCloud",
    Social_Media_Platform4 == 26 ~ "Blogging Sites",
    Social_Media_Platform4 == 27 ~ "Other",
    Social_Media_Platform4 == 28 ~ "Dark web",
    Social_Media_Platform4 == 29 ~ "Discord",
    Social_Media_Platform4 == 30 ~ "Gab",
    Social_Media_Platform4 == 31 ~ "Iron March",
    Social_Media_Platform4 == 32 ~ "Parler",
    Social_Media_Platform4 == 33 ~ "Wire",
    Social_Media_Platform4 == -99 ~ "Unknown",
    Social_Media_Platform4 == NA ~ NA
  ),
  Social_Media_Platform4 = as.factor(Social_Media_Platform4),
  Social_Media_Platform4 = fct_relevel(Social_Media_Platform4, "Facebook"),
  Social_Media_Platform5 = case_when(
    Social_Media_Platform5 == 1 ~ "Facebook",
    Social_Media_Platform5 == 2 ~ "Twitter",
    Social_Media_Platform5 == 3 ~ "YouTube",
    Social_Media_Platform5 == 4 ~ "Vimeo",
    Social_Media_Platform5 == 5 ~ "Instagram",
    Social_Media_Platform5 == 6 ~ "Flickr",
    Social_Media_Platform5 == 7 ~ "Tumblr",
    Social_Media_Platform5 == 8 ~ "Imgur",
    Social_Media_Platform5 == 9 ~ "Snapchat",
    Social_Media_Platform5 == 10 ~ "Google Plus",
    Social_Media_Platform5 == 11 ~ "Skype",
    Social_Media_Platform5 == 12 ~ "LinkedIn",
    Social_Media_Platform5 == 13 ~ "MySpace",
    Social_Media_Platform5 == 14 ~ "4chan",
    Social_Media_Platform5 == 15 ~ "Reddit",
    Social_Media_Platform5 == 16 ~ "Ask.fm",
    Social_Media_Platform5 == 17 ~ "WhatsApp",
    Social_Media_Platform5 == 18 ~ "Surespot",
    Social_Media_Platform5 == 19 ~ "Telegram",
    Social_Media_Platform5 == 20 ~ "Kik",
    Social_Media_Platform5 == 21 ~ "Paltalk",
    Social_Media_Platform5 == 22 ~ "VK",
    Social_Media_Platform5 == 23 ~ "Diaspora",
    Social_Media_Platform5 == 24 ~ "JustPaste.it",
    Social_Media_Platform5 == 25 ~ "SoundCloud",
    Social_Media_Platform5 == 26 ~ "Blogging Sites",
    Social_Media_Platform5 == 27 ~ "Other",
    Social_Media_Platform5 == 28 ~ "Dark web",
    Social_Media_Platform5 == 29 ~ "Discord",
    Social_Media_Platform5 == 30 ~ "Gab",
    Social_Media_Platform5 == 31 ~ "Iron March",
    Social_Media_Platform5 == 32 ~ "Parler",
    Social_Media_Platform5 == 33 ~ "Wire",
    Social_Media_Platform5 == -99 ~ "Unknown",
    Social_Media_Platform5 == NA ~ NA
  ),
  Social_Media_Platform5 = as.factor(Social_Media_Platform5),
  Social_Media_Platform5 = fct_relevel(Social_Media_Platform5, "Ask.fm"),
  Length_Group = case_when(
    Length_Group == -99 ~ "Unknown",
    Length_Group == -88 ~ "No Group",
    Length_Group >= 0 & Length_Group < 12 ~ "< 1 Year",
    Length_Group >= 12 & Length_Group <= 24 ~ "1-2 Years",
    Length_Group > 24 & Length_Group <= 36 ~ "2-3 Years",
    Length_Group > 36 & Length_Group <= 48 ~ "3-4 Years",
    Length_Group > 48 & Length_Group <= 60 ~ "4-5 Years",
    Length_Group > 60 ~ "> 5 Years"
  ),
  Length_Group = as.factor(Length_Group),
  Length_Group = fct_relevel(Length_Group, "< 1 Year"),
  Social_Media_Activities1 = case_when(
    Social_Media_Activities1 == 1 ~ "Consumption",
    Social_Media_Activities1 == 2 ~ "Dissemination",
    Social_Media_Activities1 == 3 ~ "Dialogue",
    Social_Media_Activities1 == 4 ~ "Creation",
    Social_Media_Activities1 == 5 ~ "Establish relation",
    Social_Media_Activities1 == 6 ~ "Foreign travel plan",
    Social_Media_Activities1 == 7 ~ "Domestic attack plan",
    Social_Media_Activities1 == -99 ~ "Unknown",
    Social_Media_Activities1 == -88 ~ "Not applicable"
  ),
  Social_Media_Activities1 = as.factor(Social_Media_Activities1),
  Social_Media_Activities1 = fct_relevel(Social_Media_Activities1, "Consumption"),
  Social_Media_Activities2 = case_when(
    Social_Media_Activities2 == 2 ~ "Dissemination",
    Social_Media_Activities2 == 3 ~ "Dialogue",
    Social_Media_Activities2 == 4 ~ "Creation",
    Social_Media_Activities2 == 5 ~ "Establish relation",
    Social_Media_Activities2 == 6 ~ "Foreign travel plan",
    Social_Media_Activities2 == 7 ~ "Domestic attack plan",
    Social_Media_Activities2 == -99 ~ "Unknown",
    Social_Media_Activities2 == -88 ~ "Not applicable",
    Social_Media_Activities2 == NA ~ NA
  ),
  Social_Media_Activities2 = as.factor(Social_Media_Activities2),
  Social_Media_Activities2 = fct_relevel(Social_Media_Activities2, "Dissemination"),
  Social_Media_Activities3 = case_when(
    Social_Media_Activities3 == 3 ~ "Dialogue",
    Social_Media_Activities3 == 4 ~ "Creation",
    Social_Media_Activities3 == 5 ~ "Establish relation",
    Social_Media_Activities3 == 6 ~ "Foreign travel plan",
    Social_Media_Activities3 == 7 ~ "Domestic attack plan",
    Social_Media_Activities3 == -99 ~ "Unknown",
    Social_Media_Activities3 == -88 ~ "Not applicable",
    Social_Media_Activities3 == NA ~ NA
  ),
  Social_Media_Activities3 = as.factor(Social_Media_Activities3),
  Social_Media_Activities3 = fct_relevel(Social_Media_Activities3, "Dialogue"),
  Social_Media_Activities4 = case_when(
    Social_Media_Activities4 == 4 ~ "Creation",
    Social_Media_Activities4 == 5 ~ "Establish relation",
    Social_Media_Activities4 == 6 ~ "Foreign travel plan",
    Social_Media_Activities4 == 7 ~ "Domestic attack plan",
    Social_Media_Activities4 == -99 ~ "Unknown",
    Social_Media_Activities4 == -88 ~ "Not applicable",
    Social_Media_Activities4 == NA ~ NA
  ),
  Social_Media_Activities4 = as.factor(Social_Media_Activities4),
  Social_Media_Activities4 = fct_relevel(Social_Media_Activities4, "Creation"),
  Social_Media_Activities5 = case_when(
    Social_Media_Activities5 == 5 ~ "Establish relation",
    Social_Media_Activities5 == 6 ~ "Foreign travel plan",
    Social_Media_Activities5 == 7 ~ "Domestic attack plan",
    Social_Media_Activities5 == -99 ~ "Unknown",
    Social_Media_Activities5 == -88 ~ "Not applicable",
    Social_Media_Activities5 == NA ~ NA
  ),
  Social_Media_Activities5 = as.factor(Social_Media_Activities5),
  Social_Media_Activities5 = fct_relevel(Social_Media_Activities5, "Establish relation"),
  Social_Media_Activities6 = case_when(
    Social_Media_Activities6 == 6 ~ "Foreign travel plan",
    Social_Media_Activities6 == 7 ~ "Domestic attack plan",
    Social_Media_Activities6 == -99 ~ "Unknown",
    Social_Media_Activities6 == -88 ~ "Not applicable",
    Social_Media_Activities6 == NA ~ NA
  ),
  Social_Media_Activities6 = as.factor(Social_Media_Activities6),
  Social_Media_Activities6 = fct_relevel(Social_Media_Activities6, "Foreign travel plan"),
  Social_Media_Activities7 = case_when(
    Social_Media_Activities7 == 7 ~ "Domestic attack plan",
    Social_Media_Activities7 == -99 ~ "Unknown",
    Social_Media_Activities7 == -88 ~ "Not applicable",
    Social_Media_Activities7 == NA ~ NA
  ),
  Social_Media_Activities7 = as.factor(Social_Media_Activities7),
  Social_Media_Activities7 = fct_relevel(Social_Media_Activities7, "Domestic attack plan"),
  Radicalization_Islamist = case_when(
    Radicalization_Islamist == 0 ~ "No",
    Radicalization_Islamist == 1 ~ "Yes",
    Radicalization_Islamist == -99 ~ "Unknown"
  ),
  Radicalization_Islamist = as.factor(Radicalization_Islamist),
  Radicalization_Islamist = fct_relevel(Radicalization_Islamist, "No"),
  Radicalization_Far_Right = case_when(
    Radicalization_Far_Right == 0 ~ "No",
    Radicalization_Far_Right == 1 ~ "Yes",
    Radicalization_Far_Right == -99 ~ "Unknown"
  ),
  Radicalization_Far_Right = as.factor(Radicalization_Far_Right),
  Radicalization_Far_Right = fct_relevel(Radicalization_Far_Right, "No"),
  Radicalization_Far_Left = case_when(
    Radicalization_Far_Left == 0 ~ "No",
    Radicalization_Far_Left == 1 ~ "Yes",
    Radicalization_Far_Left == -99 ~ "Unknown"
  ),
  Radicalization_Far_Left = as.factor(Radicalization_Far_Left),
  Radicalization_Far_Left = fct_relevel(Radicalization_Far_Left, "No"),
  Radicalization_Single_Issue = case_when(
    Radicalization_Single_Issue == 0 ~ "No",
    Radicalization_Single_Issue == 1 ~ "Yes",
    Radicalization_Single_Issue == -99 ~ "Unknown"
  ),
  Ideological_Sub_Category1 = case_when(
    Ideological_Sub_Category1 == 1 ~ "Militia/gun rights",
    Ideological_Sub_Category1 == 2 ~ "White Supremacy",
    Ideological_Sub_Category1 == 3 ~ "Xenophobia",
    Ideological_Sub_Category1 == 4 ~ "Sovereign Citizens",
    Ideological_Sub_Category1 == 5 ~ "Christian Identity",
    Ideological_Sub_Category1 == 6 ~ "Animal Rights",
    Ideological_Sub_Category1 == 7 ~ "New Left",
    Ideological_Sub_Category1 == 8 ~ "Black Nationalist",
    Ideological_Sub_Category1 == 9 ~ "Communist",
    Ideological_Sub_Category1 == 10 ~ "Anarchist",
    Ideological_Sub_Category1 == 11 ~ "Islamist",
    Ideological_Sub_Category1 == 12 ~ "PR Ind.",
    Ideological_Sub_Category1 == 13 ~ "IRA",
    Ideological_Sub_Category1 == 14 ~ "Cult",
    Ideological_Sub_Category1 == 15 ~ "Pro-Life",
    Ideological_Sub_Category1 == 16 ~ "Jewish Defense Lg.",
    Ideological_Sub_Category1 == 17 ~ "Anti-LGBTQ",
    Ideological_Sub_Category1 == 18 ~ "Other",
    Ideological_Sub_Category1 == 19 ~ "Incel",
    Ideological_Sub_Category1 == 20 ~ "Moorish SCM",
    Ideological_Sub_Category1 == 21 ~ "Pro-Trump",
    Ideological_Sub_Category1 == 22 ~ "Anti-Trump",
    Ideological_Sub_Category1 == 23 ~ "Anti-Law Enf.",
    Ideological_Sub_Category1 == 24 ~ "Pro-Choice"
  ),
  Ideological_Sub_Category1 = as.factor(Ideological_Sub_Category1),
  Ideological_Sub_Category1 = fct_relevel(Ideological_Sub_Category1, "Militia/gun rights"),
  Ideological_Sub_Category2 = case_when(
    Ideological_Sub_Category2 == 1 ~ "Militia/gun rights",
    Ideological_Sub_Category2 == 2 ~ "White Supremacy",
    Ideological_Sub_Category2 == 3 ~ "Xenophobia",
    Ideological_Sub_Category2 == 4 ~ "Sovereign Citizens",
    Ideological_Sub_Category2 == 5 ~ "Christian Identity",
    Ideological_Sub_Category2 == 6 ~ "Animal Rights",
    Ideological_Sub_Category2 == 7 ~ "New Left",
    Ideological_Sub_Category2 == 8 ~ "Black Nationalist",
    Ideological_Sub_Category2 == 9 ~ "Communist",
    Ideological_Sub_Category2 == 10 ~ "Anarchist",
    Ideological_Sub_Category2 == 11 ~ "Islamist",
    Ideological_Sub_Category2 == 12 ~ "PR Ind.",
    Ideological_Sub_Category2 == 13 ~ "IRA",
    Ideological_Sub_Category2 == 14 ~ "Cult",
    Ideological_Sub_Category2 == 15 ~ "Pro-Life",
    Ideological_Sub_Category2 == 16 ~ "Jewish Defense Lg.",
    Ideological_Sub_Category2 == 17 ~ "Anti-LGBTQ",
    Ideological_Sub_Category2 == 18 ~ "Other",
    Ideological_Sub_Category2 == 19 ~ "Incel",
    Ideological_Sub_Category2 == 20 ~ "Moorish SCM",
    Ideological_Sub_Category2 == 21 ~ "Pro-Trump",
    Ideological_Sub_Category2 == 22 ~ "Anti-Trump",
    Ideological_Sub_Category2 == 23 ~ "Anti-Law Enf.",
    Ideological_Sub_Category2 == 24 ~ "Pro-Choice"
  ),
  Ideological_Sub_Category2 = as.factor(Ideological_Sub_Category2),
  Ideological_Sub_Category2 = fct_relevel(Ideological_Sub_Category2, "Militia/gun rights"),
  Ideological_Sub_Category3 = case_when(
    Ideological_Sub_Category3 == 1 ~ "Militia/gun rights",
    Ideological_Sub_Category3 == 2 ~ "White Supremacy",
    Ideological_Sub_Category3 == 3 ~ "Xenophobia",
    Ideological_Sub_Category3 == 4 ~ "Sovereign Citizens",
    Ideological_Sub_Category3 == 5 ~ "Christian Identity",
    Ideological_Sub_Category3 == 6 ~ "Animal Rights",
    Ideological_Sub_Category3 == 7 ~ "New Left",
    Ideological_Sub_Category3 == 8 ~ "Black Nationalist",
    Ideological_Sub_Category3 == 9 ~ "Communist",
    Ideological_Sub_Category3 == 10 ~ "Anarchist",
    Ideological_Sub_Category3 == 11 ~ "Islamist",
    Ideological_Sub_Category3 == 12 ~ "PR Ind.",
    Ideological_Sub_Category3 == 13 ~ "IRA",
    Ideological_Sub_Category3 == 14 ~ "Cult",
    Ideological_Sub_Category3 == 15 ~ "Pro-Life",
    Ideological_Sub_Category3 == 16 ~ "Jewish Defense Lg.",
    Ideological_Sub_Category3 == 17 ~ "Anti-LGBTQ",
    Ideological_Sub_Category3 == 18 ~ "Other",
    Ideological_Sub_Category3 == 19 ~ "Incel",
    Ideological_Sub_Category3 == 20 ~ "Moorish SCM",
    Ideological_Sub_Category3 == 21 ~ "Pro-Trump",
    Ideological_Sub_Category3 == 22 ~ "Anti-Trump",
    Ideological_Sub_Category3 == 23 ~ "Anti-Law Enf.",
    Ideological_Sub_Category3 == 24 ~ "Pro-Choice"
  ),
  Ideological_Sub_Category3 = as.factor(Ideological_Sub_Category3),
  Ideological_Sub_Category3 = fct_relevel(Ideological_Sub_Category3, "Militia/gun rights"),
  Itinerant = case_when(
    Itinerant == 0 ~ "No",
    Itinerant == 1 ~ "Yes",
    Itinerant == -99 ~ "Unknown"
  ),
  Itinerant = as.factor(Itinerant),
  Itinerant = fct_relevel(Itinerant, "No"),
  External_Rad = case_when(
    External_Rad == 0 ~ "No",
    External_Rad == 1 ~ "Yes",
    External_Rad == -99 ~ "Unknown"
  ),
  External_Rad = as.factor(External_Rad),
  External_Rad = fct_relevel(External_Rad, "No"),
  Rad_Duration = Rad_duration,
  Rad_duration = NULL,
  Rad_Duration = case_when(
    Rad_Duration == 1 ~ "Short",
    Rad_Duration == 2 ~ "Medium",
    Rad_Duration == 3 ~ "Long",
    Rad_Duration == -99 ~ "Unknown",
    Rad_Duration == -88 ~ "Not applicable"
  ),
  Rad_Duration = as.factor(Rad_Duration),
  Rad_Duration = fct_relevel(Rad_Duration, "Short"),
  Radical_Behaviors = case_when(
    Radical_Behaviors == 0 ~ "None",
    Radical_Behaviors == 1 ~ "Association",
    Radical_Behaviors == 2 ~ "Lifestyle",
    Radical_Behaviors == 3 ~ "Convert Others",
    Radical_Behaviors == 4 ~ "Distancing",
    Radical_Behaviors == 5 ~ "Legal Activism",
    Radical_Behaviors == 6 ~ "Mat/Fin Support",
    Radical_Behaviors == 7 ~ "Operational Support",
    Radical_Behaviors == 8 ~ "Training",
    Radical_Behaviors == 9 ~ "Non-Violent Plot",
    Radical_Behaviors == 10 ~ "Violent Plot",
    Radical_Behaviors == -99 ~ "Unknown"
  ),
  Radical_Behaviors = as.factor(Radical_Behaviors),
  Radical_Behaviors = fct_relevel(Radical_Behaviors, "None"),
  Radical_Beliefs = case_when(
    Radical_Beliefs == 0 ~ "None",
    Radical_Beliefs == 1 ~ "Exposed",
    Radical_Beliefs == 2 ~ "Pursuit",
    Radical_Beliefs == 3 ~ "Full Knowledge",
    Radical_Beliefs == 4 ~ "Shared Belief",
    Radical_Beliefs == 5 ~ "Committed",
    Radical_Beliefs == -99 ~ "Unknown"
  ),
  Radical_Beliefs = as.factor(Radical_Beliefs),
  Radical_Beliefs = fct_relevel(Radical_Beliefs, "None"),
  US_Govt_Leader = case_when(
    US_Govt_Leader == 0 ~ "No",
    US_Govt_Leader == 1 ~ "Yes",
    US_Govt_Leader == -99 ~ "Unknown"
  ),
  US_Govt_Leader = as.factor(US_Govt_Leader),
  US_Govt_Leader = fct_relevel(US_Govt_Leader, "No"),
  Foreign_Govt_Leader = case_when(
    Foreign_Govt_Leader == 0 ~ "No",
    Foreign_Govt_Leader == 1 ~ "Yes",
    Foreign_Govt_Leader == -99 ~ "Unknown"
  ),
  Foreign_Govt_Leader = as.factor(Foreign_Govt_Leader),
  Foreign_Govt_Leader = fct_relevel(Foreign_Govt_Leader, "No"),
  Event_Influence1 = case_when(
    Event_Influence1 == 0 ~ "None",
    Event_Influence1 == 1 ~ "9/11",
    Event_Influence1 == 2 ~ "Vietnam War",
    Event_Influence1 == 3 ~ "Cold War",
    Event_Influence1 == 4 ~ "First Gulf War",
    Event_Influence1 == 5 ~ "Afghanistan/Iraq War",
    Event_Influence1 == 6 ~ "Ruby Ridge/Waco",
    Event_Influence1 == 7 ~ "Arab Spring",
    Event_Influence1 == 8 ~ "Other",
    Event_Influence1 == 9 ~ "Unite the Right",
    Event_Influence1 == 10 ~ "George Floyd Death",
    Event_Influence1 == 11 ~ "2016 US Election",
    Event_Influence1 == 12 ~ "COVID-19 Pandemic",
    Event_Influence1 == 13 ~ "2020 US Election",
    Event_Influence1 == -99 ~ "Unknown"
  ),
  Event_Influence1 = as.factor(Event_Influence1),
  Event_Influence1 = fct_relevel(Event_Influence1, "None"),
  Event_Influence2 = case_when(
    Event_Influence2 == 0 ~ "None",
    Event_Influence2 == 1 ~ "9/11",
    Event_Influence2 == 2 ~ "Vietnam War",
    Event_Influence2 == 3 ~ "Cold War",
    Event_Influence2 == 4 ~ "First Gulf War",
    Event_Influence2 == 5 ~ "Afghanistan/Iraq War",
    Event_Influence2 == 6 ~ "Ruby Ridge/Waco",
    Event_Influence2 == 7 ~ "Arab Spring",
    Event_Influence2 == 8 ~ "Other",
    Event_Influence2 == 9 ~ "Unite the Right",
    Event_Influence2 == 10 ~ "George Floyd Death",
    Event_Influence2 == 11 ~ "2016 US Election",
    Event_Influence2 == 12 ~ "COVID-19 Pandemic",
    Event_Influence2 == 13 ~ "2020 US Election",
    Event_Influence2 == -99 ~ "Unknown",
    Event_Influence2 = NA ~ NA
  ),
  Event_Influence2 = as.factor(Event_Influence2),
  Event_Influence2 = fct_relevel(Event_Influence2, "2020 US Election"),
  Event_Influence3 = case_when(
    Event_Influence3 == 0 ~ "None",
    Event_Influence3 == 1 ~ "9/11",
    Event_Influence3 == 2 ~ "Vietnam War",
    Event_Influence3 == 3 ~ "Cold War",
    Event_Influence3 == 4 ~ "First Gulf War",
    Event_Influence3 == 5 ~ "Afghanistan/Iraq War",
    Event_Influence3 == 6 ~ "Ruby Ridge/Waco",
    Event_Influence3 == 7 ~ "Arab Spring",
    Event_Influence3 == 8 ~ "Other",
    Event_Influence3 == 9 ~ "Unite the Right",
    Event_Influence3 == 10 ~ "George Floyd Death",
    Event_Influence3 == 11 ~ "2016 US Election",
    Event_Influence3 == 12 ~ "COVID-19 Pandemic",
    Event_Influence3 == 13 ~ "2020 US Election",
    Event_Influence3 == -99 ~ "Unknown",
    Event_Influence3 == -88 ~ NA,
    Event_Influence3 = NA ~ NA
  ),
  Event_Influence3 = as.factor(Event_Influence3),
  Event_Influence3 = fct_relevel(Event_Influence3, "2020 US Election"),
  Event_Influence4 = case_when(
    Event_Influence4 == 0 ~ "None",
    Event_Influence4 == 1 ~ "9/11",
    Event_Influence4 == 2 ~ "Vietnam War",
    Event_Influence4 == 3 ~ "Cold War",
    Event_Influence4 == 4 ~ "First Gulf War",
    Event_Influence4 == 5 ~ "Afghanistan/Iraq War",
    Event_Influence4 == 6 ~ "Ruby Ridge/Waco",
    Event_Influence4 == 7 ~ "Arab Spring",
    Event_Influence4 == 8 ~ "Other",
    Event_Influence4 == 9 ~ "Unite the Right",
    Event_Influence4 == 10 ~ "George Floyd Death",
    Event_Influence4 == 11 ~ "2016 US Election",
    Event_Influence4 == 12 ~ "COVID-19 Pandemic",
    Event_Influence4 == 13 ~ "2020 US Election",
    Event_Influence4 == -99 ~ "Unknown",
    Event_Influence4 == -88 ~ NA,
    Event_Influence4 = NA ~ NA
  ),
  Event_Influence4 = as.factor(Event_Influence4),
  Event_Influence4 = fct_relevel(Event_Influence4, "2016 US Election"),
  Radicalization_Sequence = case_when(
    Radicalization_Sequence == 1 ~ "Belief-first",
    Radicalization_Sequence == 2 ~ "Behavior-first",
    Radicalization_Sequence == 3 ~ "Simultaneous",
    Radicalization_Sequence == -99 ~ "Unknown"
  ),
  Radicalization_Sequence = as.factor(Radicalization_Sequence),
  Radicalization_Sequence = fct_relevel(Radicalization_Sequence, "Belief-first"),
  Radicalization_Place = case_when(
    Radicalization_Place == 0 ~ "No",
    Radicalization_Place == 1 ~ "Place of worship",
    Radicalization_Place == 2 ~ "Educational inst.",
    Radicalization_Place == 3 ~ "Social club",
    Radicalization_Place == -99 ~ "Unknown"
  ),
  Radicalization_Place = as.factor(Radicalization_Place),
  Radicalization_Place = fct_relevel(Radicalization_Place, "No"),
  Prison_Radicalize = case_when(
    Prison_Radicalize == 0 ~ "No",
    Prison_Radicalize == 1 ~ "Before",
    Prison_Radicalize == 2 ~ "After",
    Prison_Radicalize == 3 ~ "During",
    Prison_Radicalize == -99 ~ "Unknown",
    Prison_Radicalize == -88 ~ "Not applicable"
  ),
  Prison_Radicalize = as.factor(Prison_Radicalize),
  Prison_Radicalize = fct_relevel(Prison_Radicalize, "No"),
  Broad_Ethnicity = case_when(
    Broad_Ethnicity == 1 ~ "Hispanic/Latino",
    Broad_Ethnicity == 2 ~ "Black",
    Broad_Ethnicity == 3 ~ "White",
    Broad_Ethnicity == 4 ~ "ME/NA",
    Broad_Ethnicity == 5 ~ "Native American",
    Broad_Ethnicity == 6 ~ "Asian",
    Broad_Ethnicity == 7 ~ "Other",
    Broad_Ethnicity == -99 ~ "Unknown"
  ),
  Broad_Ethnicity = as.factor(Broad_Ethnicity),
  Broad_Ethnicity = fct_relevel(Broad_Ethnicity, "White"),
  Marital_Status = case_when(
    Marital_Status == 1 ~ "Single (NM)",
    Marital_Status == 2 ~ "Married",
    Marital_Status == 3 ~ "Divorced",
    Marital_Status == 4 ~ "Widowed",
    Marital_Status == -99 ~ "Unknown"
  ),
  Marital_Status = as.factor(Marital_Status),
  Marital_Status = fct_relevel(Marital_Status, "Single (NM)"),
  Sex = case_when(
    Sex == 1 ~ "Female",
    Sex == 2 ~ "Male"
  ),
  Sex = as.factor(Sex),
  Sex = fct_relevel(Sex, "Female"),
  Religious_Background = case_when(
    Religious_Background == 1 ~ "Sunni",
    Religious_Background == 2 ~ "Shi\'a",
    Religious_Background == 3 ~ "Sufi",
    Religious_Background == 4 ~ "Other Islam",
    Religious_Background == 5 ~ "Unspec. Islam",
    Religious_Background == 6 ~ "Evangelical",
    Religious_Background == 7 ~ "Mainline",
    Religious_Background == 8 ~ "Catholic",
    Religious_Background == 9 ~ "Orthodox",
    Religious_Background == 10 ~ "Other Christ.",
    Religious_Background == 11 ~ "Unspec. Christ.",
    Religious_Background == 12 ~ "Jewish",
    Religious_Background == 13 ~ "Buddhist",
    Religious_Background == 14 ~ "Hindu",
    Religious_Background == 15 ~ "New religion",
    Religious_Background == 16 ~ "Agnostic",
    Religious_Background == 17 ~ "Athiest",
    Religious_Background == 18 ~ "Other",
    Religious_Background == -99 ~ "Unknown"
  ),
  Religious_Background = as.factor(Religious_Background),
  Religious_Background = fct_relevel(Religious_Background, "Athiest"),
  Convert = case_when(
    Convert == 0 ~ "No",
    Convert == 1 ~ "Before",
    Convert == 2 ~ "During",
    Convert == 3 ~ "After",
    Convert == -99 ~ "Unknown"
  ),
  Convert = as.factor(Convert),
  Convert = fct_relevel(Convert, "No"),
  Reawakening = case_when(
    Reawakening == 0 ~ "No",
    Reawakening == 1 ~ "Prior",
    Reawakening == 2 ~ "During",
    Reawakening == 3 ~ "After",
    Reawakening == -99 ~ "Unknown"
  ),
  Reawakening = as.factor(Reawakening),
  Reawakening = fct_relevel(Reawakening, "No"),
  Residency_Status = case_when(
    Residency_Status == 1 ~ "Born citizen",
    Residency_Status == 2 ~ "Naturalized",
    Residency_Status == 3 ~ "Legal Permanent",
    Residency_Status == 4 ~ "Temporary",
    Residency_Status == 5 ~ "Undocumented",
    Residency_Status == -99 ~ "Unknown"
  ),
  Residency_Status = as.factor(Residency_Status),
  Residency_Status = fct_relevel(Residency_Status, "Born citizen"),
  Immigrant_Generation = case_when(
    Immigrant_Generation == 0 ~ "3+ generations",
    Immigrant_Generation == 1 ~ "1st generation",
    Immigrant_Generation == 2 ~ "2nd generation",
    Immigrant_Generation == -99 ~ "Unknown"
  ),
  Immigrant_Generation = as.factor(Immigrant_Generation),
  Immigrant_Generation = fct_relevel(Immigrant_Generation, "3+ generations"),
  Education = case_when(
    Education == 1 ~ "No HS",
    Education == 2 ~ "Some HS",
    Education == 3 ~ "HS Diploma",
    Education == 4 ~ "Some college",
    Education == 5 ~ "College degree",
    Education == 6 ~ "Some VS",
    Education == 7 ~ "VS degree",
    Education == 8 ~ "Some master's",
    Education == 9 ~ "Master's degree",
    Education == 10 ~ "Some PhD",
    Education == 11 ~ "PhD",
    Education == -99 ~ "Unknown"
  ),
  Education = as.factor(Education),
  Education = fct_relevel(Education, "No HS"),
  Student = case_when(
    Student == 0 ~ "No",
    Student == 1 ~ "Yes",
    Student == -99 ~ "Unknown"
  ),
  Student = as.factor(Student),
  Student = fct_relevel(Student, "No"),
  Employment_Status = case_when(
    Employment_Status == 1 ~ "Employed",
    Employment_Status == 2 ~ "Self-employed",
    Employment_Status == 3 ~ "Unemployed looking",
    Employment_Status == 4 ~ "Unemployed",
    Employment_Status == 5 ~ "Student",
    Employment_Status == 6 ~ "Retired",
    Employment_Status == -99 ~ "Unknown"
  ),
  Employment_Status = as.factor(Employment_Status),
  Employment_Status = fct_relevel(Employment_Status, "Employed"),
  Work_History = case_when(
    Work_History == 1 ~ "Long-term Unemp.",
    Work_History == 2 ~ "Underemployed",
    Work_History == 3 ~ "Serially Employed",
    Work_History == 4 ~ "Regularly Employed",
    Work_History == -99 ~ "Unknown",
    Work_History == -88 ~ "Not applicable"
  ),
  Work_History = as.factor(Work_History),
  Work_History = fct_relevel(Work_History, "Long-term Unemp."),
  Military = case_when(
    Military == 0 ~ "No",
    Military == 1 ~ "Yes",
    Military == -99 ~ "Unknown"
  ),
  Military = as.factor(Military),
  Military = fct_relevel(Military, "No"),
  Military_Status_Arrest = case_when(
    Military_Status_Arrest == 0 ~ "Inactive",
    Military_Status_Arrest == 1 ~ "Active",
    Military_Status_Arrest == -88 ~ "Never Served",
    Military_Status_Arrest == -99 ~ "Unknown"
  ),
  Military_Status_Arrest = as.factor(Military_Status_Arrest),
  Military_Status_Arrest = fct_relevel(Military_Status_Arrest, "Inactive"),
  Foreign_Military = case_when(
    Foreign_Military == 0 ~ "No",
    Foreign_Military == 1 ~ "Yes",
    Foreign_Military == -99 ~ "Unknown"
  ),
  Foreign_Military = as.factor(Foreign_Military),
  Foreign_Military = fct_relevel(Foreign_Military, "No"),
  Social_Stratum_Childhood = case_when(
    Social_Stratum_Childhood == 1 ~ "Low",
    Social_Stratum_Childhood == 2 ~ "Middle",
    Social_Stratum_Childhood == 3 ~ "High",
    Social_Stratum_Childhood == -99 ~ "Unknown"
  ),
  Social_Stratum_Childhood = as.factor(Social_Stratum_Childhood),
  Social_Stratum_Childhood = fct_relevel(Social_Stratum_Childhood, "Low"),
  Social_Stratum_Adulthood = case_when(
    Social_Stratum_Adulthood == 1 ~ "Low",
    Social_Stratum_Adulthood == 2 ~ "Middle",
    Social_Stratum_Adulthood == 3 ~ "High",
    Social_Stratum_Adulthood == -99 ~ "Unknown",
    Social_Stratum_Adulthood == -88 ~ "Not applicable"
  ),
  Social_Stratum_Adulthood = as.factor(Social_Stratum_Adulthood),
  Social_Stratum_Adulthood = fct_relevel(Social_Stratum_Adulthood, "Low"),
  Abuse_Child = case_when(
    Abuse_Child == 0 ~ "No",
    Abuse_Child == 1 ~ "Yes (non-family)",
    Abuse_Child == 2 ~ "Yes (family)",
    Abuse_Child == 3 ~ "Yes (both)"
  ),
  Abuse_Child = as.factor(Abuse_Child),
  Abuse_Child = fct_relevel(Abuse_Child, "No"),
  Abuse_Adult = case_when(
    Abuse_Adult == 0 ~ "No",
    Abuse_Adult == 1 ~ "Yes (non-family)",
    Abuse_Adult == 2 ~ "Yes (family)",
    Abuse_Adult == 3 ~ "Yes (both)",
    Abuse_Adult == -88 ~ "Not applicable"
  ),
  Abuse_Adult = as.factor(Abuse_Adult),
  Abuse_Adult = fct_relevel(Abuse_Adult, "No"),
  Abuse_Type1 = case_when(
    Abuse_Type1 == 1 ~ "Sexual",
    Abuse_Type1 == 2 ~ "Physical",
    Abuse_Type1 == 3 ~ "Emotional",
    Abuse_Type1 == -99 ~ "Unknown",
    Abuse_Type1 == -88 ~ "No Abuse"
  ),
  Abuse_Type1 = as.factor(Abuse_Type1),
  Abuse_Type1 = fct_relevel(Abuse_Type1, "Sexual"),
  Abuse_Type2 = case_when(
    Abuse_Type2 == 1 ~ "Sexual",
    Abuse_Type2 == 2 ~ "Physical",
    Abuse_Type2 == 3 ~ "Emotional",
    Abuse_Type2 == -99 ~ "Unknown",
    Abuse_Type2 == -88 ~ "No Abuse",
    Abuse_Type2 == NA ~ NA
  ),
  Abuse_Type2 = as.factor(Abuse_Type2),
  Abuse_Type2 = fct_relevel(Abuse_Type2, "Sexual"),
  Abuse_Type3 = case_when(
    Abuse_Type3 == 1 ~ "Sexual",
    Abuse_Type3 == 2 ~ "Physical",
    Abuse_Type3 == 3 ~ "Emotional",
    Abuse_Type3 == -99 ~ "Unknown",
    Abuse_Type3 == -88 ~ "No Abuse",
    Abuse_Type3 == NA ~ NA
  ),
  Abuse_Type3 = as.factor(Abuse_Type3),
  Abuse_Type3 = fct_relevel(Abuse_Type3, "Sexual"),
  Psychological = case_when(
    Psychological == 0 ~ "None",
    Psychological == 1 ~ "Speculated",
    Psychological == 2 ~ "Diagnosed"
  ),
  Psychological = as.factor(Psychological),
  Psychological = fct_relevel(Psychological, "None"),
  Alcohol_Drug = case_when(
    Alcohol_Drug == 0 ~ "No",
    Alcohol_Drug == 1 ~ "Yes"
  ),
  Alcohol_Drug = as.factor(Alcohol_Drug),
  Alcohol_Drug = fct_relevel(Alcohol_Drug, "No"),
  Radical_Friend = case_when(
    Radical_Friend == 0 ~ "No",
    Radical_Friend == 1 ~ "Legal",
    Radical_Friend == 2 ~ "Nonviolent",
    Radical_Friend == 3 ~ "Violent",
    Radical_Friend == -99 ~ "Unknown"
  ),
  Radical_Friend = as.factor(Radical_Friend),
  Radical_Friend = fct_relevel(Radical_Friend, "No"),
  Radical_Family = case_when(
    Radical_Family == 0 ~ "No",
    Radical_Family == 1 ~ "Legal",
    Radical_Family == 2 ~ "Nonviolent",
    Radical_Family == 3 ~ "Violent",
    Radical_Family == -99 ~ "Unknown"
  ),
  Radical_Family = as.factor(Radical_Family),
  Radical_Family = fct_relevel(Radical_Family, "No"),
  Radical_Signif_Other = case_when(
    Radical_Signif_Other == 0 ~ "No",
    Radical_Signif_Other == 1 ~ "Legal",
    Radical_Signif_Other == 2 ~ "Nonviolent",
    Radical_Signif_Other == 3 ~ "Violent",
    Radical_Signif_Other == -99 ~ "Unknown"
  ),
  Radical_Signif_Other = as.factor(Radical_Signif_Other),
  Radical_Signif_Other = fct_relevel(Radical_Signif_Other, "No"),
  Previous_Criminal_Activity = case_when(
    Previous_Criminal_Activity == 0 ~ "None",
    Previous_Criminal_Activity == 1 ~ "Misdemeanors",
    Previous_Criminal_Activity == 2 ~ "Felony",
    Previous_Criminal_Activity == 3 ~ "Violent",
    Previous_Criminal_Activity == -99 ~ "Unknown"
  ),
  Previous_Criminal_Activity = as.factor(Previous_Criminal_Activity),
  Previous_Criminal_Activity = fct_relevel(Previous_Criminal_Activity, "None"),
  Previous_Criminal_Activity_Type1 = case_when(
    Previous_Criminal_Activity_Type1 == 1 ~ "Homicide",
    Previous_Criminal_Activity_Type1 == 2 ~ "Rape",
    Previous_Criminal_Activity_Type1 == 3 ~ "Robbery",
    Previous_Criminal_Activity_Type1 == 4 ~ "Aggravated Assault",
    Previous_Criminal_Activity_Type1 == 5 ~ "Burglary",
    Previous_Criminal_Activity_Type1 == 6 ~ "Larceny-theft",
    Previous_Criminal_Activity_Type1 == 7 ~ "Motor theft",
    Previous_Criminal_Activity_Type1 == 8 ~ "Arson",
    Previous_Criminal_Activity_Type1 == 9 ~ "Simple Assault",
    Previous_Criminal_Activity_Type1 == 10 ~ "Fraud",
    Previous_Criminal_Activity_Type1 == 11 ~ "Forgery",
    Previous_Criminal_Activity_Type1 == 12 ~ "Embezzlement",
    Previous_Criminal_Activity_Type1 == 13 ~ "DUI/DWI",
    Previous_Criminal_Activity_Type1 == 14 ~ "Prostitution",
    Previous_Criminal_Activity_Type1 == 15 ~ "Vandalism",
    Previous_Criminal_Activity_Type1 == 16 ~ "Drug-related",
    Previous_Criminal_Activity_Type1 == 17 ~ "Parole violation",
    Previous_Criminal_Activity_Type1 == 18 ~ "Firearm-related",
    Previous_Criminal_Activity_Type1 == 19 ~ "Domestic violence",
    Previous_Criminal_Activity_Type1 == 20 ~ "Other",
    Previous_Criminal_Activity_Type1 == -99 ~ "Unknown",
    Previous_Criminal_Activity_Type1 == -88 ~ "No crime"
  ),
  Previous_Criminal_Activity_Type1 = as.factor(Previous_Criminal_Activity_Type1),
  Previous_Criminal_Activity_Type1 = fct_relevel(Previous_Criminal_Activity_Type1, "Aggravated Assault"),
  Previous_Criminal_Activity_Type2 = case_when(
    Previous_Criminal_Activity_Type2 == 1 ~ "Homicide",
    Previous_Criminal_Activity_Type2 == 2 ~ "Rape",
    Previous_Criminal_Activity_Type2 == 3 ~ "Robbery",
    Previous_Criminal_Activity_Type2 == 4 ~ "Aggravated Assault",
    Previous_Criminal_Activity_Type2 == 5 ~ "Burglary",
    Previous_Criminal_Activity_Type2 == 6 ~ "Larceny-theft",
    Previous_Criminal_Activity_Type2 == 7 ~ "Motor theft",
    Previous_Criminal_Activity_Type2 == 8 ~ "Arson",
    Previous_Criminal_Activity_Type2 == 9 ~ "Simple Assault",
    Previous_Criminal_Activity_Type2 == 10 ~ "Fraud",
    Previous_Criminal_Activity_Type2 == 11 ~ "Forgery",
    Previous_Criminal_Activity_Type2 == 12 ~ "Embezzlement",
    Previous_Criminal_Activity_Type2 == 13 ~ "DUI/DWI",
    Previous_Criminal_Activity_Type2 == 14 ~ "Prostitution",
    Previous_Criminal_Activity_Type2 == 15 ~ "Vandalism",
    Previous_Criminal_Activity_Type2 == 16 ~ "Drug-related",
    Previous_Criminal_Activity_Type2 == 17 ~ "Parole violation",
    Previous_Criminal_Activity_Type2 == 18 ~ "Firearm-related",
    Previous_Criminal_Activity_Type2 == 19 ~ "Domestic violence",
    Previous_Criminal_Activity_Type2 == 20 ~ "Other",
    Previous_Criminal_Activity_Type2 == -99 ~ "Unknown",
    Previous_Criminal_Activity_Type2 == -88 ~ "No crime",
    Previous_Criminal_Activity_Type2 == NA ~ NA
  ),
  Previous_Criminal_Activity_Type2 = as.factor(Previous_Criminal_Activity_Type2),
  Previous_Criminal_Activity_Type2 = fct_relevel(Previous_Criminal_Activity_Type2, "Aggravated Assault"),
  Previous_Criminal_Activity_Type3 = case_when(
    Previous_Criminal_Activity_Type3 == 1 ~ "Homicide",
    Previous_Criminal_Activity_Type3 == 2 ~ "Rape",
    Previous_Criminal_Activity_Type3 == 3 ~ "Robbery",
    Previous_Criminal_Activity_Type3 == 4 ~ "Aggravated Assault",
    Previous_Criminal_Activity_Type3 == 5 ~ "Burglary",
    Previous_Criminal_Activity_Type3 == 6 ~ "Larceny-theft",
    Previous_Criminal_Activity_Type3 == 7 ~ "Motor theft",
    Previous_Criminal_Activity_Type3 == 8 ~ "Arson",
    Previous_Criminal_Activity_Type3 == 9 ~ "Simple Assault",
    Previous_Criminal_Activity_Type3 == 10 ~ "Fraud",
    Previous_Criminal_Activity_Type3 == 11 ~ "Forgery",
    Previous_Criminal_Activity_Type3 == 12 ~ "Embezzlement",
    Previous_Criminal_Activity_Type3 == 13 ~ "DUI/DWI",
    Previous_Criminal_Activity_Type3 == 14 ~ "Prostitution",
    Previous_Criminal_Activity_Type3 == 15 ~ "Vandalism",
    Previous_Criminal_Activity_Type3 == 16 ~ "Drug-related",
    Previous_Criminal_Activity_Type3 == 17 ~ "Parole violation",
    Previous_Criminal_Activity_Type3 == 18 ~ "Firearm-related",
    Previous_Criminal_Activity_Type3 == 19 ~ "Domestic violence",
    Previous_Criminal_Activity_Type3 == 20 ~ "Other",
    Previous_Criminal_Activity_Type3 == -99 ~ "Unknown",
    Previous_Criminal_Activity_Type3 == -88 ~ "No crime",
    Previous_Criminal_Activity_Type3 == NA ~ NA
  ),
  Previous_Criminal_Activity_Type3 = as.factor(Previous_Criminal_Activity_Type3),
  Previous_Criminal_Activity_Type3 = fct_relevel(Previous_Criminal_Activity_Type3, "Aggravated Assault"),
  Previous_Criminal_Activity_Age = case_when(
    Previous_Criminal_Activity_Age == 1 ~ "Under 18",
    Previous_Criminal_Activity_Age == 2 ~ "18-24",
    Previous_Criminal_Activity_Age == 3 ~ "25-34",
    Previous_Criminal_Activity_Age == 4 ~ "35-44",
    Previous_Criminal_Activity_Age == 5 ~ "Over 45",
    Previous_Criminal_Activity_Age == -99 ~ "Unknown",
    Previous_Criminal_Activity_Age == -88 ~ "No crime"
  ),
  Previous_Criminal_Activity_Age = as.factor(Previous_Criminal_Activity_Age),
  Previous_Criminal_Activity_Age = fct_relevel(Previous_Criminal_Activity_Age, "Under 18"),
  Gang = case_when(
    Gang == 0 ~ "No",
    Gang == 1 ~ "Street gang",
    Gang == 2 ~ "Org. crime",
    Gang == 3 ~ "Both",
    Gang == -99 ~ "Unknown"
  ),
  Gang = as.factor(Gang),
  Gang = fct_relevel(Gang, "No"),
  Gang_Age_Joined = case_when(
    Gang_Age_Joined == 1 ~ "Under 8",
    Gang_Age_Joined == 2 ~ "8-12",
    Gang_Age_Joined == 3 ~ "13-19",
    Gang_Age_Joined == 4 ~ "20-39",
    Gang_Age_Joined == 5 ~ "40-64",
    Gang_Age_Joined == 6 ~ "Over 65",
    Gang_Age_Joined == -99 ~ "Unknown",
    Gang_Age_Joined == -88 ~ "No gang"
  ),
  Gang_Age_Joined = as.factor(Gang_Age_Joined),
  Gang_Age_Joined = fct_relevel(Gang_Age_Joined, "8-12"),
  Trauma = case_when(
    Trauma == 0 ~ "No",
    Trauma == 1 ~ "Yes (time unknown)",
    Trauma == 2 ~ "Yes (long before)",
    Trauma == 3 ~ "Yes (short before)",
    Trauma == -99 ~ "Unknown"
  ),
  Trauma = as.factor(Trauma),
  Trauma = fct_relevel(Trauma, "No"),
  Other_Ideologies = case_when(
    Other_Ideologies == 0 ~ "No",
    Other_Ideologies == 1 ~ "Yes",
    Other_Ideologies == -99 ~ "Unknown"
  ),
  Other_Ideologies = as.factor(Other_Ideologies),
  Other_Ideologies = fct_relevel(Other_Ideologies, "No"),
  Angry_US = case_when(
    Angry_US == 0 ~ "No",
    Angry_US == 1 ~ "Yes",
    Angry_US == -99 ~ "Unknown"
  ),
  Angry_US = as.factor(Angry_US),
  Angry_US = fct_relevel(Angry_US, "No"),
  Group_Grievance = case_when(
    Group_Grievance == 0 ~ "No",
    Group_Grievance == 1 ~ "Yes (no connection)",
    Group_Grievance == 2 ~ "Yes (connection)",
    Group_Grievance == 3 ~ "Yes (experience)",
    Group_Grievance == -99 ~ "Unknown"
  ),
  Group_Grievance = as.factor(Group_Grievance),
  Group_Grievance = fct_relevel(Group_Grievance, "No"),
  Component_ID = as.numeric(Component_ID),
  Component_Density = as.double(Component_Density),
  Lone_Offender = case_when(
    Lone_Offender == 0 ~ "No",
    Lone_Offender == 1 ~ "Yes"
  ),
  Lone_Offender = as.factor(Lone_Offender),
  Degree_Centrality = as.numeric(Degree_Centrality),
  Betweenness_Centrality = as.double(Betweenness_Centrality),
  Closeness_Centrality = as.double(Closeness_Centrality),
  Children = case_when(
    Children == -99 ~ 0,
    TRUE ~ Children
  )
  )

write_csv(pirus_encoded, "pirus_encoded.csv")